version: '3.8'

services:
  # Alumni Backend Service
  alumni-backend:
    image: ghcr.io/phm-oh/alumni-registration-system:latest
    container_name: alumni-backend
    ports:
      - "5500:5500"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5500
    restart: unless-stopped
    networks:
      - alumni-network
    volumes:
      - alumni_uploads:/app/uploads
      - alumni_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # เพิ่มเวลา start_period
    labels:
      - "project=alumni"
      - "service=backend"
      - "environment=production"

  # Alumni Frontend Service
  alumni-frontend:
    image: ghcr.io/phm-oh/fontend-alumni:latest
    container_name: alumni-frontend
    ports:
      - "3001:80"  # Internal access port
    environment:
      - VITE_ENV=production
      # เพิ่ม env vars อื่นๆ ที่อาจจำเป็น
      - VITE_APP_NAME=Alumni Registration System
      - VITE_COLLEGE_NAME=Udon Thani Vocational College
    depends_on:
      alumni-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - alumni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health || http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "project=alumni"
      - "service=frontend"
      - "environment=production"

  # Alumni Nginx Proxy - Main Entry Point
  alumni-nginx:
    image: nginx:alpine
    container_name: alumni-nginx
    ports:
      - "3000:80"  # Users access here
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      alumni-frontend:
        condition: service_healthy
      alumni-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - alumni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "project=alumni"
      - "service=proxy"
      - "environment=production"

networks:
  alumni-network:
    driver: bridge
    name: alumni-network
    # เพิ่ม isolation เพื่อไม่ให้ conflict กับ chatqa
    enable_ipv6: false

volumes:
  alumni_uploads:
    driver: local
    name: alumni_uploads
  alumni_logs:
    driver: local
    name: alumni_logs