version: '3.8'

services:
  # Alumni Backend Service
  alumni-backend:
    image: ghcr.io/phm-oh/alumni-registration-system:latest
    container_name: alumni-backend
    ports:
      - "5500:5500"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=5500
    restart: unless-stopped
    networks:
      - alumni-network
    volumes:
      - alumni_uploads:/app/uploads
      - alumni_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "project=alumni"
      - "service=backend"
      - "environment=production"

  # Alumni Frontend Service
  alumni-frontend:
    image: ghcr.io/phm-oh/fontend-alumni:latest
    container_name: alumni-frontend
    # üéØ ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏à‡∏≤‡∏Å 3000 ‡πÄ‡∏õ‡πá‡∏ô 3001 ‡πÄ‡∏û‡∏∑‡πà‡∏≠‡πÑ‡∏°‡πà‡πÉ‡∏´‡πâ user ‡πÄ‡∏Ç‡πâ‡∏≤‡∏ï—Ä‡∏á
    ports:
      - "3001:80"
    environment:
      - VITE_ENV=production
    depends_on:
      alumni-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - alumni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "project=alumni"
      - "service=frontend"
      - "environment=production"

  # üéØ Nginx ‡πÄ‡∏õ‡πá‡∏ô main entry point
  alumni-nginx:
    image: nginx:alpine
    container_name: alumni-nginx
    ports:
      - "3000:80"  # ‡∏ú‡∏π‡πâ‡πÉ‡∏ä‡πâ‡πÄ‡∏Ç‡πâ‡∏≤‡∏ó‡∏µ‡πà port 3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - alumni-frontend
      - alumni-backend
    restart: unless-stopped
    networks:
      - alumni-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    labels:
      - "project=alumni"
      - "service=proxy"
      - "environment=production"

networks:
  alumni-network:
    driver: bridge
    name: alumni-network

volumes:
  alumni_uploads:
    driver: local
    name: alumni_uploads
  alumni_logs:
    driver: local
    name: alumni_logs